### ISSUE TITLE
[Feature Request] Single-Shot Force Constant Fit

### ISSUE THREAD

**Issue by ejmeitz** [tdep-developers/tdep#113]
Would it be possible to add a flag to the `extract_forcecosntants` command that lets you fit all the orders at once instead of fitting to the residuals of the force (which I believe is what occurs right now). I'd like to be able to compare the two within TDEP and use the rest of TDEP's functionality. Using something like ALAMODE I've found a couple scenarios where fitting all at once gives a better fit.

 I swear in a long ago version there was a `--residual` flag but I could be wrong.

**Comment by flokno** [comment]
I know what you mean -- this feature was available a long time ago but has been removed and I pretty sure is not available anymore. Doing all orders all at once can yield a better fit, but is then not "strict" TDEP in the sense of [1]. In TDEP, orders are fitted consecutively so that they become smaller and smaller. Fitting all orders is more in the spirit of a Taylor expansion, like hiphive is also doing.

​ [1] A. Castellano, J. P. A. Batista, and M. J. Verstraete, J. Chem. Phys. 159, 234501 (2023).

**Comment by ejmeitz** [comment]
Makes sense. 

So physically, TDEP is finding the set of phonons which best describe the system even if that means a worse fit to the energy? How does one reconcile that difference? When you predict observables with the effective Hamiltonian you get worse predictions in the TDEP sense. Is it expected that the phonon modes found by TDEP are more faithful to the actual material? (I saw your newest paper on arxiv which gave a more stable ground for TDEP to stand on but it is a bit beyond my understanding at the moment)

**Comment by ollehellman** [comment]
So, if you fit say a fourth order model all at once there is nothing that guarantees that the lower order terms are smaller than the higher order terms. In that case you are way off the perturbative regime, and there is no practical way of getting any reliable observable from the model. In practice you are back at square one with a new unsolvable problem.

By fitting in descending order you are variational with respect to the free energy at each order (even if you don't know the third order free energy exactly, if you could calculate it it would be variational). You also guarantee that the second order is largest, and the higher orders become smaller and smaller. This brings you back into the perturbative regime so that you can access observables.

In weakly anharmonic materials fitting everything at once or to the residual does not give a meaningful difference in practice. But if the two schemes do give significantly different results, that is a case where you definitely want to fit to the residuals.

**Comment by flokno** [comment]
Let me just add this to make the point more clear: In the quartic double well, the "true" second order will likely be of negative slope, i.e., there is not even a positive definite starting point for your perturbation series, even before asking the question whether the "perturbation" is small in any sense.

Of course it would be interesting to hear more about the particular cases and how large the differences between the fitting strategies are. We can pull you on our slack channel to discuss this more privately if you want

**Comment by ejmeitz** [comment]
These arguments make sense. Fitting residuals does guarantee the terms have smaller and smaller contributions, but fitting all at once does not necessarily mean the terms won't behave that way. Would it still be preferable to fit residuals in that case? Is there some theory about which approach actually gives the correct renormalized phonons (I'm not sure "correct" is well defined here). There's papers like [this](https://journals.aps.org/prb/abstract/10.1103/PhysRevB.108.184307) from Northwestern that investigate the many different ways you could in principle calculate IFCs. Ultimately they all give rather different thermal conductivity predictions. I can think of several qualitative reasons of why one approach might be best, but I think TDEP might be the only one with mathematical backing.

I also understand that for most lattice properties assume perturbation theory must hold, but that does not mean the actual potential energy surface behaves that way. So if you only care about energy prediction does it really matter which way you fit. For my case I am interested in heat capacity (willing to share plots on slack) which relies only on the energy. In each case I will get slightly different phonon modes, but fitting all at once is much better at predicting heat capacity than fitting to residuals. For Stillinger-Weber silicon (which is really harmonic) the two approaches are similar like Olle said, but for Lennard-Jones argon (which is really anharmonic) there is a stark difference in the heat capacity predicted when compared to the ground truth.

**Comment by mjv500** [comment]
Super interesting if you can see differences. In the paper Florian pointed
to Alois showed that tdep is exact in the sense that the static average is
what is measured experimentally. Your Cv should also have anharmonic
contributions right? So if it looks better with the global fit then I think
some compensation of errors is happening. Happy to compare and look into it
on slack.

Best

Matthieu

**Comment by flokno** [comment]
@ejmeitz if you want to join the slack channel, write me a mail at my work address which should be easy to find
