### ISSUE TITLE
Convert TDEP force constants as inputs for other BTE codes

### ISSUE THREAD

**Issue by ZKC19940412** [tdep-developers/tdep#31]
Hi, thank you all so much for the previous help. I have managed to install the TDEP code in my workstation and used it to explore the system I want. I had got a decent dispersions and working on getting the thermal conductivity. I used the all the commands as suggested in the tutorial. However, I found that the thermal conductivity routine is quiet memory intensive and I can only afforded to do an 8 8 8 grid point calculation for my 320 atom supercell (5 atom unit cell, 4x4x4 replications). Therefore, I have two questions as follow:

1. Is this memory intensiveness as expected ? Is there anyway I can check/trace the memory usage so that I can use thermal conductivity routine within TDEP to perform calculations using larger grid points?

2. Any tips you would suggest so that I can convert the second and third order force constants from my tdep fitting to be the inputs of other BTE codes? Such as ShengBTE, phono3py or even the newly emerged kALDo?

Thank you so much for reading this post and proving useful feedback?

Best, 
Zekun

**Comment by flokno** [comment]
for 1): I recently ran thermal conductivity for a monoclinic system with 12 atoms in the unit cell up to 23x23x23 q-point grid with >10k cores on a supercomputer with AMD Epyc CPUs. You might need to use less cores per node to free up some memory, but otherwise this is just normal MPI memory-parallel supercomputing, nothing special.

for 2): no this is currently not possible.
