### ISSUE TITLE
Regarding the ELASTIC CONSTANTS (GPa) output by TDEP

### ISSUE THREAD

**Issue by obaica** [tdep-developers/tdep#50]
We take the cubic phase `Cs2AgBiBr6` as an example, with the `POSCAR` structure file shown below. 

```
Cs2AgBiBr6                              
   1.00000000000000     
     0.0000000000000000    5.5936662721923289    5.5936662721923289
     5.5936662721923280    0.0000000000000000    5.5936662721923289
     5.5936662721923289    5.5936662721923289   -0.0000000000000000
   Ag   Bi   Cs   Br
     1     1     2     6
Direct
  0.0000000000000000 -0.0000000000000000  0.0000000000000000
  0.5000000000000000  0.5000000000000000  0.5000000000000000
  0.2500000000000000  0.2500000000000000  0.2500000000000000
  0.7500000000000000  0.7500000000000000  0.7500000000000000
  0.7539642048802042  0.2460357951197958  0.2460357951197958
  0.2460357951197958  0.7539642048802042  0.7539642048802042
  0.2460357951197958  0.7539642048802042  0.2460357951197958
  0.7539642048802042  0.2460357951197958  0.7539642048802042
  0.2460357951197958  0.2460357951197958  0.7539642048802042
  0.7539642048802042  0.7539642048802042  0.2460357951197958
```

First, molecular dynamics at `350 K (40 ps)` was conducted, followed by processing through TDEP to obtain the high-temperature phonon spectrum (as shown in the attached phonon diagram).

<img width="367" alt="phonon" src="https://github.com/tdep-developers/tdep/assets/22672466/62ba1f87-b430-45e7-874e-2a25daa18cdf">

Based on the output from TDEP (as in the attached `tdep-output.txt file`), we obtained the following output for the elastic constants:

```
 ELASTIC CONSTANTS (GPa):
          44.37513           9.46643           9.46643           0.00000           0.00000           0.00000
           9.46643          44.37513           9.46643           0.00000           0.00000           0.00000
           9.46643           9.46643          44.37513           0.00000           0.00000           0.00000
           0.00000           0.00000           0.00000           6.12996           0.00000           0.00000
           0.00000           0.00000           0.00000           0.00000           6.12996           0.00000
           0.00000           0.00000           0.00000           0.00000           0.00000           6.12996
```

From the above, we can determine C11 = 44.37 GPa, C12 = 9.47 GPa; C44 = 6.13 GPa.

Simultaneously, we obtained the elastic constants by calculating the slope of the acoustic branches to obtain the speed of sound (the specific principle refers to [Materials and Design 32 (2011) 3231–3239](https://doi.org/10.1016/j.matdes.2011.02.043)):

C11 = 24.4 GPa, C12 = 14.3 GPa; C44 = 5.0 GPa

A comparison reveals **a significant discrepancy in C11**, and we have yet to find a specific reason (we conducted the same test with Si, and the results from both methods were very close).

Therefore, I would like to know on 
**1) what principle the elastic constants obtained from TDEP's output file are based?**
**2) Secondly, what is the unit of the horizontal axis in TDEP's outfile.dispersion_relations file?**

[tdep-output.txt](https://github.com/tdep-developers/tdep/files/14789727/tdep-output.txt)
[outfile.dispersion_relations.txt](https://github.com/tdep-developers/tdep/files/14790263/outfile.dispersion_relations.txt)

**Comment by OrbitalC** [comment]
Hello,

1)

The elastic constants in TDEP are computed from the second order interatomic force constants (IFC), using a formula that you can find in [Appl. Phys. Lett. 107, 231901 (2015)](http://dx.doi.org/10.1063/1.4936896) for example (eq. 2)
(This formula can be derived by taking derivative of the effective harmonic potential energy with respect to strains).

Elastic constants computed this way are very sensitive to the convergence of the IFC, the size of the simulation and the cutoff used, so much so that you might need supercell size that can become really expensive for DFT simulations for some systems.
If you are interested in the temperature evolution of the elastic constants, the paper mentioned previously gives an approach  using TDEP for the temperature evolution and the stress-strain relation you used for the 0K values (eq. 3).

2)

The horizontal axis is related to the accumulated length in reciprocal space along the path. Since the code is working internally in atomic units, it should be in 1/Bohr.

**Comment by obaica** [comment]
Thank you for your detailed response. Your explanation is very clear.
